# Generated by Django 4.1.5 on 2023-03-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_alter_department_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Names')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Names')),
                ('job', models.CharField(choices=[('0', 'Accountant'), ('1', 'Manager'), ('2', 'Economist'), ('3', 'Other')], max_length=50, verbose_name='Job')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
