# Generated by Django 4.1.7 on 2023-03-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
    ]
