# Generated by Django 4.1.7 on 2023-03-09 04:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_avatar_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
